### ISSUE TITLE
 #include <ESP8266WiFiMulti.h>

### ISSUE THREAD

**Issue by nightscoutro** [skjelland/wdrip#1]
Hello,

ESP8266WiFiMulti.h: where did you get this particular library from?
I can't seem to find any version that works...the only that I almost made it work returned an error when compiling, complaining about include <vector>...

Thanks!

**Comment by skjelland** [comment]
Removed unused includes.  It should now work with the standard esp8266 wifi library installed with the ide

http://esp8266.github.io/Arduino/versions/2.1.0/doc/libraries.html
